[providers.php]
server = "apache"

[phases.setup]
cmds = ["apt-get update && apt-get install -y libapache2-mod-php"]

[phases.build]
cmds = ["mkdir -p assets/img/book_covers && chmod -R 777 assets/img/book_covers"]